### OTHERS ###
#bbedit
#betterzip # Preview archives
#electrum
#lastfm
#libreoffice
#liteicon
#microsoft-office
#opera
#station
#steam
#thunderbird
#vlc
#yujitach-menumeters
1password
1password-cli
KeePassXC
adium
adobe-acrobat-reader
adobe-digital-editions
aegisub
aerial
alfred
altserver
android-file-transfer
android-studio
appcleaner
archiver
atom
balenaetcher
banktivity
brackets
brave-browser
browserosaurus
cakebrew
cheatsheet
chromium
cisdem-data-recovery
cisdem-pdf-converter-ocr
clion
cliqz
coconutbattery
code-notes
corona-tracker
cryptomator
customshortcuts
cyberduck
daisydisk
dash
db-browser-for-sqlite
deltawalker
discord
disk-inventory-x
do-not-disturb
docker
dozer
dropbox
emby-server
epic-games
expressvpn
fantastical
filebot
finicky
firefox
firefox-developer-edition
fliqlo
flume
folx
font-hack
font-sans-forgetica
font-source-sans-pro
fork
forklift
gas-mask
geektool
gemini
ghost
gitahead
gitfinder
github
gitkraken
gitpigeon
google-chrome
google-drive-file-stream
google-earth-pro
gopanel
gopanel # kmutahar/tap
gpg-suite
gpg-suite-no-mail
handbrake
hazeover
homebrew/cask-versions/soulver2
iina
imazing
inkscape
insomnia
istat-menus
iterm2
keepassxc
keeweb
keka
keybase
kmutahar/tap/gopanel
kmutahar/tap/musixmatch
kmutahar/tap/unclutter
knockknock
lastpass
launchpad-manager
lightpaper
little-snitch
local
local-by-flywheel
maccy
macpass
mactex
macupdater
malwarebytes
mark-text
mediainfo
meetingbar
megacmd
megasync
microsoft-auto-update
microsoft-office
microsoft-office-2016
mkvtoolnix
mkvtools
mono-mdk
mono-mdk-for-visual-studio
mp4tools
musixmatch # kmutahar/tap
netiquette
netnewswire
nextcloud
notable
notion
obs
one-switch
onyx
openoffice
opera
osxfuse
oversight
photosweeper-x
plex
plex-media-player
plex-media-server
pluralsight
proxyman
qladdict
qladdict # Lets you view subtitles .srt files
qlcolorcode # Preview source code files with syntax highlighting
qlimagesize # Display image size and resolution
qlmarkdown # Preview Markdown files
qlmobi # Preview Kindle ebook formats (prc, mobi, azw, azw3, azw4, pdb)
qlprettypatch # Preview .patch files
qlstephen # Preview plain text files without or with unknown file extension. Example: README, CHANGELOG, index.styl, etc.
qlvideo # Preview most types of video files, as well as their thumbnails, cover art and metadata
quicklook-csv # Preview CSV files
quicklook-json # Preview JSON files
quicknfo # Previewing NFO files
radarr
ransomwhere
reikey
resilio-sync
rocket
rocket-typist
screaming-frog-seo-spider
sdformatter
sequel-pro
signal
slack
sonarr
soulver
soulver2 # homebrew/cask-versions
sourcetree
spotify
spotify-now-playing
ssh-config-editor
station
sublime-merge
sublime-text
subtools
suspicious-package # Preview the contents of a standard Apple installer package
syncthing
telegram
termius
the-unarchiver
thunderbird
ti-connect-ce
timing
tor-browser
tower
transmission
tunnelblick
tuxera-ntfs
ukelele
unclutter
veracrypt
vienna
virtualbox
visual-studio
visual-studio-code
vlc
vmware-fusion
vscodium
wd-drive-utilities
website-watchman
whatsapp
wifi-explorer
ynab
zettlr
zoho-mail
zoom

jetbrains-toolbox
phpstorm
qtpass
quicklook-csv  # Preview CSV files
